# Generated by Django 4.1.6 on 2023-02-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='instructor_contact',
            field=models.CharField(default='Not Available', max_length=13, verbose_name='phone'),
        ),
    ]
