# Generated by Django 4.1.6 on 2023-02-10 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_details_instructor_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allcourses',
            options={'verbose_name': 'Allcourse', 'verbose_name_plural': 'Allcourses'},
        ),
    ]
