# Generated by Django 4.1.6 on 2023-02-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_alter_allcourses_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='instructor_contact',
        ),
        migrations.AddField(
            model_name='allcourses',
            name='instructor_contact',
            field=models.CharField(default='Not Available', max_length=13, verbose_name='phone'),
        ),
    ]
