# Generated by Django 4.1.6 on 2023-02-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_remove_details_instructor_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='instructorSupported',
        ),
        migrations.RemoveField(
            model_name='details',
            name='selfStudy',
        ),
        migrations.AddField(
            model_name='details',
            name='no_of_books',
            field=models.CharField(default='Enter here', max_length=100),
        ),
        migrations.AddField(
            model_name='details',
            name='no_of_pages',
            field=models.CharField(default='Enter here', max_length=1000),
        ),
    ]
