# Generated by Django 4.1.6 on 2023-02-10 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_remove_details_instructorsupported_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='details',
            options={'verbose_name': 'Details', 'verbose_name_plural': 'Details'},
        ),
    ]
